from typing import Any
from django.db import models

# Create your models here.

class Task(models.Model): 
    class Status(models.TextChoices): # TODO does backend need display version of status'?
        TODO = "TODO", "To Do"
        IN_PROGRESS = "IN_PROGRESS", "In Progress"
        DONE = "DONE", "Done"

    # Primary key is Autogenerated ID by default

    title = models.TextField(max_length=255)

    # longer, optional description
    description = models.TextField(blank=True, null=True) 

    status = models.CharField(max_length=15, choices=Status.choices, default=Status.TODO)
    due_datetime = models.DateTimeField()

    # for debugging
    def __str__(self):
        return self.title